baseURL = "https://pentesttime.org/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Pentesttime"

theme = "uBlogger-v.2.0.1"

[params]
  version = "2.0.X"
  description = "CTFs and penetration testing guides"
  defaultTheme = "dark"
  [params.page]
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 1000
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      # URL of the LOGO
      logo = "/favicon-32x32.png"
      # title name
      name = "PentestTime.org"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""

  [params.footer]
    enable = true
    # uBlogger NEW | 0.2.0 Custom content (HTML format is supported)
    custom = "<a href='https://en.wikipedia.org/wiki/KISS_principle'>KISS-(Keep It Simple, Stupid).</a>"
    # uBlogger NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # uBlogger NEW | 0.2.0 whether to show copyright info
    copyright = true
    # uBlogger NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2021
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # uBlogger NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 5
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # uBlogger NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 10
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # uBlogger NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # uBlogger CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Pentesting tips and tricks."
      # subtitle shown in home page
      subtitle = "Try Harder!."
      # whether to show social links
      social = true
      # uBlogger NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # uBlogger DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "rohitkumarankam"
    Linkedin = "rohitkumarankam"
    Twitter = "rohitkumarankam"
    Email = "rohit@rka.li"
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-41TFGX6H14"
      # whether to anonymize IP
      anonymizeIP = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "📚"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
#  [[menu.main]]
#    identifier = "tags"
#    pre = ""
#    post = ""
#    name = "🏷️Tags"
#    url = "/tags/"
#    title = ""
#    weight = 2
#  [[menu.main]]
#    identifier = "categories"
#    pre = ""
#    post = ""
#    name = "🐈Categories"
#    url = "/categories/"
#    title = ""
#    weight = 3

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":filename"

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
