baseURL = "https://pentesttime.org/"

defaultContentLanguage = "en"

languageCode = "en"
title = "PentestTime - Pentesting tips and tricks"

ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
theme = "LoveIt"
enableGitInfo = true
enableRobotsTXT = true
summaryLength = 200
[params]
  # LoveIt theme version
  version = "0.2.X"
  defaultTheme = "dark"
  description = "PentestTime is a collection of tips and tricks for pentesting."
  gitRepo = "https://github.com/rohitkumarankam/pentesttime.org"
  dateFormat = "2006-01-02"
  images = ["https://pentesttime.org/images/meta-screenshot.jpg"]
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
        logo = "/favicon-32x32.png"
        name = "pentesttime.org"
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    since = "2021"
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      # gravatarEmail = 'rohitkumarankam@gmail.com'
      avatarURL= "/profile.webp"
      title = "Pentesting tips and tricks."
      subtitle = "Try Harder!."
      typeit = true
      social = true
  [params.social]
    github = "rohitkumarankam"
    linkedin = "rohitkumarankam"
    twitter = "rohitkumarankam"
    # Youtubecustom = "rohitkumarankam"
    email = "rohit@rka.li"


  [params.app]
    title = "Pentesttime"
  [params.search]
    enable = true
    type = "lunr"
    contentLength = "4000"
    placeholder = ""
    maxResultsLength = 10
    snippetLength = 30
    hilightTag = "em"
    absoluteURL = false
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = false
    fraction = false
    fontawesome = false
    linkToMarkdown = true
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
    [params.page.comment]
        enable = false
    [params.page.code]
        copy = true
        maxShownLines = 1000
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "6549898"
      # whether to anonymize IP
      anonymizeIP = false
  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "📚"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "🏷️"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = "🐈"
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "ctf.ac"
    pre = "🔗"
    post = ""
    url = "https://ctf.ac"
    name = "CTF.AC"
    title = ""
    weight = 4

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6



[author]
  name = "Rohit Kumar Ankam"
  email = "rohit@rka.li"
  link = "https://rohitkumarankam.com/"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"



# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # LoveIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]